#!/bin/bash

# This script pretends to be the coreos-installer binary

set -euo pipefail

lines="Installing Red Hat Enterprise Linux CoreOS 48.84.202107202156-0 (Ootpa) x86_64 (512-byte sectors)
Read disk 119.2 MiB/3.7 GiB (3%)
Read disk 210.6 MiB/3.7 GiB (5%)
Read disk 310.4 MiB/3.7 GiB (8%)
Read disk 444.8 MiB/3.7 GiB (11%)
Read disk 575.4 MiB/3.7 GiB (15%)
Read disk 728.2 MiB/3.7 GiB (19%)
Read disk 879.6 MiB/3.7 GiB (23%)
Read disk 1.0 GiB/3.7 GiB (27%)
Read disk 1.2 GiB/3.7 GiB (31%)
Read disk 1.3 GiB/3.7 GiB (35%)
Read disk 1.4 GiB/3.7 GiB (37%)
Read disk 1.4 GiB/3.7 GiB (39%)
Read disk 1.5 GiB/3.7 GiB (40%)
Read disk 1.6 GiB/3.7 GiB (42%)
Read disk 1.6 GiB/3.7 GiB (44%)
Read disk 1.7 GiB/3.7 GiB (46%)
Read disk 1.8 GiB/3.7 GiB (48%)
Read disk 1.9 GiB/3.7 GiB (50%)
Read disk 2.0 GiB/3.7 GiB (53%)
Read disk 2.0 GiB/3.7 GiB (54%)
Read disk 2.1 GiB/3.7 GiB (57%)
Read disk 2.2 GiB/3.7 GiB (59%)
Read disk 2.3 GiB/3.7 GiB (61%)
Read disk 2.3 GiB/3.7 GiB (63%)
Read disk 2.4 GiB/3.7 GiB (65%)
Read disk 2.5 GiB/3.7 GiB (66%)
Read disk 2.5 GiB/3.7 GiB (67%)
Read disk 2.6 GiB/3.7 GiB (69%)
Read disk 2.6 GiB/3.7 GiB (71%)
Read disk 2.7 GiB/3.7 GiB (73%)
Read disk 2.8 GiB/3.7 GiB (75%)
Read disk 2.8 GiB/3.7 GiB (77%)
Read disk 2.9 GiB/3.7 GiB (78%)
Read disk 3.0 GiB/3.7 GiB (82%)
Read disk 3.1 GiB/3.7 GiB (83%)
Read disk 3.1 GiB/3.7 GiB (84%)
Read disk 3.2 GiB/3.7 GiB (87%)
Read disk 3.3 GiB/3.7 GiB (89%)
Read disk 3.3 GiB/3.7 GiB (90%)
Read disk 3.4 GiB/3.7 GiB (92%)
Read disk 3.5 GiB/3.7 GiB (93%)
Read disk 3.5 GiB/3.7 GiB (94%)
Read disk 3.5 GiB/3.7 GiB (95%)
Read disk 3.6 GiB/3.7 GiB (96%)
Read disk 3.7 GiB/3.7 GiB (99%)
Read disk 3.7 GiB/3.7 GiB (100%)
Read disk 3.7 GiB/3.7 GiB (100%)
Writing Ignition config
Modifying kernel arguments
Install complete.
Done writing image to disk"

while read -r line; do
    echo $line
    sleep 1
done <<< $lines
