// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/omertuc/assisted-swarm/models"
)

// CreateNewAgentReader is a Reader for the CreateNewAgent structure.
type CreateNewAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNewAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNewAgentCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateNewAgentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateNewAgentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateNewAgentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateNewAgentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateNewAgentCreated creates a CreateNewAgentCreated with default headers values
func NewCreateNewAgentCreated() *CreateNewAgentCreated {
	return &CreateNewAgentCreated{}
}

/* CreateNewAgentCreated describes a response with status code 201, with default header values.

Success.
*/
type CreateNewAgentCreated struct {
	Payload *models.Agent
}

func (o *CreateNewAgentCreated) Error() string {
	return fmt.Sprintf("[POST /agents][%d] createNewAgentCreated  %+v", 201, o.Payload)
}
func (o *CreateNewAgentCreated) GetPayload() *models.Agent {
	return o.Payload
}

func (o *CreateNewAgentCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Agent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewAgentBadRequest creates a CreateNewAgentBadRequest with default headers values
func NewCreateNewAgentBadRequest() *CreateNewAgentBadRequest {
	return &CreateNewAgentBadRequest{}
}

/* CreateNewAgentBadRequest describes a response with status code 400, with default header values.

Error.
*/
type CreateNewAgentBadRequest struct {
	Payload *models.Error
}

func (o *CreateNewAgentBadRequest) Error() string {
	return fmt.Sprintf("[POST /agents][%d] createNewAgentBadRequest  %+v", 400, o.Payload)
}
func (o *CreateNewAgentBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateNewAgentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewAgentUnauthorized creates a CreateNewAgentUnauthorized with default headers values
func NewCreateNewAgentUnauthorized() *CreateNewAgentUnauthorized {
	return &CreateNewAgentUnauthorized{}
}

/* CreateNewAgentUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type CreateNewAgentUnauthorized struct {
	Payload *models.Error
}

func (o *CreateNewAgentUnauthorized) Error() string {
	return fmt.Sprintf("[POST /agents][%d] createNewAgentUnauthorized  %+v", 401, o.Payload)
}
func (o *CreateNewAgentUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateNewAgentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewAgentForbidden creates a CreateNewAgentForbidden with default headers values
func NewCreateNewAgentForbidden() *CreateNewAgentForbidden {
	return &CreateNewAgentForbidden{}
}

/* CreateNewAgentForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type CreateNewAgentForbidden struct {
	Payload *models.Error
}

func (o *CreateNewAgentForbidden) Error() string {
	return fmt.Sprintf("[POST /agents][%d] createNewAgentForbidden  %+v", 403, o.Payload)
}
func (o *CreateNewAgentForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateNewAgentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewAgentInternalServerError creates a CreateNewAgentInternalServerError with default headers values
func NewCreateNewAgentInternalServerError() *CreateNewAgentInternalServerError {
	return &CreateNewAgentInternalServerError{}
}

/* CreateNewAgentInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type CreateNewAgentInternalServerError struct {
	Payload *models.Error
}

func (o *CreateNewAgentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /agents][%d] createNewAgentInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateNewAgentInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateNewAgentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
