// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/omertuc/assisted-swarm/models"
)

// NewCreateNewAgentParams creates a new CreateNewAgentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateNewAgentParams() *CreateNewAgentParams {
	return &CreateNewAgentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNewAgentParamsWithTimeout creates a new CreateNewAgentParams object
// with the ability to set a timeout on a request.
func NewCreateNewAgentParamsWithTimeout(timeout time.Duration) *CreateNewAgentParams {
	return &CreateNewAgentParams{
		timeout: timeout,
	}
}

// NewCreateNewAgentParamsWithContext creates a new CreateNewAgentParams object
// with the ability to set a context for a request.
func NewCreateNewAgentParamsWithContext(ctx context.Context) *CreateNewAgentParams {
	return &CreateNewAgentParams{
		Context: ctx,
	}
}

// NewCreateNewAgentParamsWithHTTPClient creates a new CreateNewAgentParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateNewAgentParamsWithHTTPClient(client *http.Client) *CreateNewAgentParams {
	return &CreateNewAgentParams{
		HTTPClient: client,
	}
}

/* CreateNewAgentParams contains all the parameters to send to the API endpoint
   for the create new agent operation.

   Typically these are written to a http.Request.
*/
type CreateNewAgentParams struct {

	/* NewAgentParams.

	   Create new agent for swarm.
	*/
	NewAgentParams *models.NewAgentParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create new agent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNewAgentParams) WithDefaults() *CreateNewAgentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create new agent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNewAgentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create new agent params
func (o *CreateNewAgentParams) WithTimeout(timeout time.Duration) *CreateNewAgentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create new agent params
func (o *CreateNewAgentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create new agent params
func (o *CreateNewAgentParams) WithContext(ctx context.Context) *CreateNewAgentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create new agent params
func (o *CreateNewAgentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create new agent params
func (o *CreateNewAgentParams) WithHTTPClient(client *http.Client) *CreateNewAgentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create new agent params
func (o *CreateNewAgentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNewAgentParams adds the newAgentParams to the create new agent params
func (o *CreateNewAgentParams) WithNewAgentParams(newAgentParams *models.NewAgentParams) *CreateNewAgentParams {
	o.SetNewAgentParams(newAgentParams)
	return o
}

// SetNewAgentParams adds the newAgentParams to the create new agent params
func (o *CreateNewAgentParams) SetNewAgentParams(newAgentParams *models.NewAgentParams) {
	o.NewAgentParams = newAgentParams
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNewAgentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.NewAgentParams != nil {
		if err := r.SetBodyParam(o.NewAgentParams); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
