// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/omertuc/assisted-swarm/models"
)

// DeleteAgentReader is a Reader for the DeleteAgent structure.
type DeleteAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAgentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAgentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAgentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAgentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAgentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAgentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAgentNoContent creates a DeleteAgentNoContent with default headers values
func NewDeleteAgentNoContent() *DeleteAgentNoContent {
	return &DeleteAgentNoContent{}
}

/* DeleteAgentNoContent describes a response with status code 204, with default header values.

Success
*/
type DeleteAgentNoContent struct {
}

func (o *DeleteAgentNoContent) Error() string {
	return fmt.Sprintf("[DELETE /agents/{agent_id}][%d] deleteAgentNoContent ", 204)
}

func (o *DeleteAgentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAgentBadRequest creates a DeleteAgentBadRequest with default headers values
func NewDeleteAgentBadRequest() *DeleteAgentBadRequest {
	return &DeleteAgentBadRequest{}
}

/* DeleteAgentBadRequest describes a response with status code 400, with default header values.

Error.
*/
type DeleteAgentBadRequest struct {
	Payload *models.Error
}

func (o *DeleteAgentBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /agents/{agent_id}][%d] deleteAgentBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteAgentBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteAgentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentUnauthorized creates a DeleteAgentUnauthorized with default headers values
func NewDeleteAgentUnauthorized() *DeleteAgentUnauthorized {
	return &DeleteAgentUnauthorized{}
}

/* DeleteAgentUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type DeleteAgentUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteAgentUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /agents/{agent_id}][%d] deleteAgentUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteAgentUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteAgentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentForbidden creates a DeleteAgentForbidden with default headers values
func NewDeleteAgentForbidden() *DeleteAgentForbidden {
	return &DeleteAgentForbidden{}
}

/* DeleteAgentForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type DeleteAgentForbidden struct {
	Payload *models.Error
}

func (o *DeleteAgentForbidden) Error() string {
	return fmt.Sprintf("[DELETE /agents/{agent_id}][%d] deleteAgentForbidden  %+v", 403, o.Payload)
}
func (o *DeleteAgentForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteAgentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentNotFound creates a DeleteAgentNotFound with default headers values
func NewDeleteAgentNotFound() *DeleteAgentNotFound {
	return &DeleteAgentNotFound{}
}

/* DeleteAgentNotFound describes a response with status code 404, with default header values.

Not Found.
*/
type DeleteAgentNotFound struct {
	Payload *models.Error
}

func (o *DeleteAgentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /agents/{agent_id}][%d] deleteAgentNotFound  %+v", 404, o.Payload)
}
func (o *DeleteAgentNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteAgentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentInternalServerError creates a DeleteAgentInternalServerError with default headers values
func NewDeleteAgentInternalServerError() *DeleteAgentInternalServerError {
	return &DeleteAgentInternalServerError{}
}

/* DeleteAgentInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type DeleteAgentInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteAgentInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /agents/{agent_id}][%d] deleteAgentInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteAgentInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteAgentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
