// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExitReader is a Reader for the Exit structure.
type ExitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewExitNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExitNoContent creates a ExitNoContent with default headers values
func NewExitNoContent() *ExitNoContent {
	return &ExitNoContent{}
}

/* ExitNoContent describes a response with status code 204, with default header values.

Success.
*/
type ExitNoContent struct {
}

func (o *ExitNoContent) Error() string {
	return fmt.Sprintf("[GET /exit][%d] exitNoContent ", 204)
}

func (o *ExitNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
