// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/omertuc/assisted-swarm/models"
)

// GetAgentReader is a Reader for the GetAgent structure.
type GetAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAgentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAgentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAgentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAgentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAgentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAgentOK creates a GetAgentOK with default headers values
func NewGetAgentOK() *GetAgentOK {
	return &GetAgentOK{}
}

/* GetAgentOK describes a response with status code 200, with default header values.

Success
*/
type GetAgentOK struct {
	Payload *models.Agent
}

func (o *GetAgentOK) Error() string {
	return fmt.Sprintf("[GET /agents/{agent_id}][%d] getAgentOK  %+v", 200, o.Payload)
}
func (o *GetAgentOK) GetPayload() *models.Agent {
	return o.Payload
}

func (o *GetAgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Agent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentBadRequest creates a GetAgentBadRequest with default headers values
func NewGetAgentBadRequest() *GetAgentBadRequest {
	return &GetAgentBadRequest{}
}

/* GetAgentBadRequest describes a response with status code 400, with default header values.

Error.
*/
type GetAgentBadRequest struct {
	Payload *models.Error
}

func (o *GetAgentBadRequest) Error() string {
	return fmt.Sprintf("[GET /agents/{agent_id}][%d] getAgentBadRequest  %+v", 400, o.Payload)
}
func (o *GetAgentBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentUnauthorized creates a GetAgentUnauthorized with default headers values
func NewGetAgentUnauthorized() *GetAgentUnauthorized {
	return &GetAgentUnauthorized{}
}

/* GetAgentUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type GetAgentUnauthorized struct {
	Payload *models.Error
}

func (o *GetAgentUnauthorized) Error() string {
	return fmt.Sprintf("[GET /agents/{agent_id}][%d] getAgentUnauthorized  %+v", 401, o.Payload)
}
func (o *GetAgentUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentForbidden creates a GetAgentForbidden with default headers values
func NewGetAgentForbidden() *GetAgentForbidden {
	return &GetAgentForbidden{}
}

/* GetAgentForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type GetAgentForbidden struct {
	Payload *models.Error
}

func (o *GetAgentForbidden) Error() string {
	return fmt.Sprintf("[GET /agents/{agent_id}][%d] getAgentForbidden  %+v", 403, o.Payload)
}
func (o *GetAgentForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentNotFound creates a GetAgentNotFound with default headers values
func NewGetAgentNotFound() *GetAgentNotFound {
	return &GetAgentNotFound{}
}

/* GetAgentNotFound describes a response with status code 404, with default header values.

Not Found.
*/
type GetAgentNotFound struct {
	Payload *models.Error
}

func (o *GetAgentNotFound) Error() string {
	return fmt.Sprintf("[GET /agents/{agent_id}][%d] getAgentNotFound  %+v", 404, o.Payload)
}
func (o *GetAgentNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentInternalServerError creates a GetAgentInternalServerError with default headers values
func NewGetAgentInternalServerError() *GetAgentInternalServerError {
	return &GetAgentInternalServerError{}
}

/* GetAgentInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type GetAgentInternalServerError struct {
	Payload *models.Error
}

func (o *GetAgentInternalServerError) Error() string {
	return fmt.Sprintf("[GET /agents/{agent_id}][%d] getAgentInternalServerError  %+v", 500, o.Payload)
}
func (o *GetAgentInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
