// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/omertuc/assisted-swarm/models"
)

// ListAgentsReader is a Reader for the ListAgents structure.
type ListAgentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAgentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAgentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAgentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListAgentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListAgentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListAgentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAgentsOK creates a ListAgentsOK with default headers values
func NewListAgentsOK() *ListAgentsOK {
	return &ListAgentsOK{}
}

/* ListAgentsOK describes a response with status code 200, with default header values.

Success
*/
type ListAgentsOK struct {
	Payload models.AgentList
}

func (o *ListAgentsOK) Error() string {
	return fmt.Sprintf("[GET /agents][%d] listAgentsOK  %+v", 200, o.Payload)
}
func (o *ListAgentsOK) GetPayload() models.AgentList {
	return o.Payload
}

func (o *ListAgentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAgentsBadRequest creates a ListAgentsBadRequest with default headers values
func NewListAgentsBadRequest() *ListAgentsBadRequest {
	return &ListAgentsBadRequest{}
}

/* ListAgentsBadRequest describes a response with status code 400, with default header values.

Error.
*/
type ListAgentsBadRequest struct {
	Payload *models.Error
}

func (o *ListAgentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /agents][%d] listAgentsBadRequest  %+v", 400, o.Payload)
}
func (o *ListAgentsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListAgentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAgentsUnauthorized creates a ListAgentsUnauthorized with default headers values
func NewListAgentsUnauthorized() *ListAgentsUnauthorized {
	return &ListAgentsUnauthorized{}
}

/* ListAgentsUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type ListAgentsUnauthorized struct {
	Payload *models.Error
}

func (o *ListAgentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /agents][%d] listAgentsUnauthorized  %+v", 401, o.Payload)
}
func (o *ListAgentsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListAgentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAgentsForbidden creates a ListAgentsForbidden with default headers values
func NewListAgentsForbidden() *ListAgentsForbidden {
	return &ListAgentsForbidden{}
}

/* ListAgentsForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type ListAgentsForbidden struct {
	Payload *models.Error
}

func (o *ListAgentsForbidden) Error() string {
	return fmt.Sprintf("[GET /agents][%d] listAgentsForbidden  %+v", 403, o.Payload)
}
func (o *ListAgentsForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListAgentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAgentsInternalServerError creates a ListAgentsInternalServerError with default headers values
func NewListAgentsInternalServerError() *ListAgentsInternalServerError {
	return &ListAgentsInternalServerError{}
}

/* ListAgentsInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type ListAgentsInternalServerError struct {
	Payload *models.Error
}

func (o *ListAgentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /agents][%d] listAgentsInternalServerError  %+v", 500, o.Payload)
}
func (o *ListAgentsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListAgentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
