// Code generated by go-swagger; DO NOT EDIT.

// Package restapi AssistedSwarm
//
//  Assisted swarm
//  Schemes:
//    http
//  Host: api.assisted-swarm.com
//  BasePath: /api/assisted-swarm
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
