// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/omertuc/assisted-swarm/models"
)

// CreateNewAgentCreatedCode is the HTTP code returned for type CreateNewAgentCreated
const CreateNewAgentCreatedCode int = 201

/*CreateNewAgentCreated Success.

swagger:response createNewAgentCreated
*/
type CreateNewAgentCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Agent `json:"body,omitempty"`
}

// NewCreateNewAgentCreated creates CreateNewAgentCreated with default headers values
func NewCreateNewAgentCreated() *CreateNewAgentCreated {

	return &CreateNewAgentCreated{}
}

// WithPayload adds the payload to the create new agent created response
func (o *CreateNewAgentCreated) WithPayload(payload *models.Agent) *CreateNewAgentCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new agent created response
func (o *CreateNewAgentCreated) SetPayload(payload *models.Agent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewAgentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateNewAgentBadRequestCode is the HTTP code returned for type CreateNewAgentBadRequest
const CreateNewAgentBadRequestCode int = 400

/*CreateNewAgentBadRequest Error.

swagger:response createNewAgentBadRequest
*/
type CreateNewAgentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateNewAgentBadRequest creates CreateNewAgentBadRequest with default headers values
func NewCreateNewAgentBadRequest() *CreateNewAgentBadRequest {

	return &CreateNewAgentBadRequest{}
}

// WithPayload adds the payload to the create new agent bad request response
func (o *CreateNewAgentBadRequest) WithPayload(payload *models.Error) *CreateNewAgentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new agent bad request response
func (o *CreateNewAgentBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewAgentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateNewAgentUnauthorizedCode is the HTTP code returned for type CreateNewAgentUnauthorized
const CreateNewAgentUnauthorizedCode int = 401

/*CreateNewAgentUnauthorized Unauthorized.

swagger:response createNewAgentUnauthorized
*/
type CreateNewAgentUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateNewAgentUnauthorized creates CreateNewAgentUnauthorized with default headers values
func NewCreateNewAgentUnauthorized() *CreateNewAgentUnauthorized {

	return &CreateNewAgentUnauthorized{}
}

// WithPayload adds the payload to the create new agent unauthorized response
func (o *CreateNewAgentUnauthorized) WithPayload(payload *models.Error) *CreateNewAgentUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new agent unauthorized response
func (o *CreateNewAgentUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewAgentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateNewAgentForbiddenCode is the HTTP code returned for type CreateNewAgentForbidden
const CreateNewAgentForbiddenCode int = 403

/*CreateNewAgentForbidden Forbidden.

swagger:response createNewAgentForbidden
*/
type CreateNewAgentForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateNewAgentForbidden creates CreateNewAgentForbidden with default headers values
func NewCreateNewAgentForbidden() *CreateNewAgentForbidden {

	return &CreateNewAgentForbidden{}
}

// WithPayload adds the payload to the create new agent forbidden response
func (o *CreateNewAgentForbidden) WithPayload(payload *models.Error) *CreateNewAgentForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new agent forbidden response
func (o *CreateNewAgentForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewAgentForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateNewAgentInternalServerErrorCode is the HTTP code returned for type CreateNewAgentInternalServerError
const CreateNewAgentInternalServerErrorCode int = 500

/*CreateNewAgentInternalServerError Error.

swagger:response createNewAgentInternalServerError
*/
type CreateNewAgentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateNewAgentInternalServerError creates CreateNewAgentInternalServerError with default headers values
func NewCreateNewAgentInternalServerError() *CreateNewAgentInternalServerError {

	return &CreateNewAgentInternalServerError{}
}

// WithPayload adds the payload to the create new agent internal server error response
func (o *CreateNewAgentInternalServerError) WithPayload(payload *models.Error) *CreateNewAgentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new agent internal server error response
func (o *CreateNewAgentInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewAgentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
