// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/omertuc/assisted-swarm/models"
)

// NewCreateNewAgentParams creates a new CreateNewAgentParams object
//
// There are no default values defined in the spec.
func NewCreateNewAgentParams() CreateNewAgentParams {

	return CreateNewAgentParams{}
}

// CreateNewAgentParams contains all the bound params for the create new agent operation
// typically these are obtained from a http.Request
//
// swagger:parameters CreateNewAgent
type CreateNewAgentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Create new agent for swarm.
	  In: body
	*/
	NewAgentParams *models.NewAgentParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateNewAgentParams() beforehand.
func (o *CreateNewAgentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.NewAgentParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("newAgentParams", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewAgentParams = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
