// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAgentHandlerFunc turns a function with the right signature into a delete agent handler
type DeleteAgentHandlerFunc func(DeleteAgentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAgentHandlerFunc) Handle(params DeleteAgentParams) middleware.Responder {
	return fn(params)
}

// DeleteAgentHandler interface for that can handle valid delete agent params
type DeleteAgentHandler interface {
	Handle(DeleteAgentParams) middleware.Responder
}

// NewDeleteAgent creates a new http.Handler for the delete agent operation
func NewDeleteAgent(ctx *middleware.Context, handler DeleteAgentHandler) *DeleteAgent {
	return &DeleteAgent{Context: ctx, Handler: handler}
}

/* DeleteAgent swagger:route DELETE /agents/{agent_id} swarm deleteAgent

Delete agent.

*/
type DeleteAgent struct {
	Context *middleware.Context
	Handler DeleteAgentHandler
}

func (o *DeleteAgent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAgentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
