// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ExitNoContentCode is the HTTP code returned for type ExitNoContent
const ExitNoContentCode int = 204

/*ExitNoContent Success.

swagger:response exitNoContent
*/
type ExitNoContent struct {
}

// NewExitNoContent creates ExitNoContent with default headers values
func NewExitNoContent() *ExitNoContent {

	return &ExitNoContent{}
}

// WriteResponse to the client
func (o *ExitNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
