// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/omertuc/assisted-swarm/models"
)

// GetAgentOKCode is the HTTP code returned for type GetAgentOK
const GetAgentOKCode int = 200

/*GetAgentOK Success

swagger:response getAgentOK
*/
type GetAgentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Agent `json:"body,omitempty"`
}

// NewGetAgentOK creates GetAgentOK with default headers values
func NewGetAgentOK() *GetAgentOK {

	return &GetAgentOK{}
}

// WithPayload adds the payload to the get agent o k response
func (o *GetAgentOK) WithPayload(payload *models.Agent) *GetAgentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agent o k response
func (o *GetAgentOK) SetPayload(payload *models.Agent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentBadRequestCode is the HTTP code returned for type GetAgentBadRequest
const GetAgentBadRequestCode int = 400

/*GetAgentBadRequest Error.

swagger:response getAgentBadRequest
*/
type GetAgentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAgentBadRequest creates GetAgentBadRequest with default headers values
func NewGetAgentBadRequest() *GetAgentBadRequest {

	return &GetAgentBadRequest{}
}

// WithPayload adds the payload to the get agent bad request response
func (o *GetAgentBadRequest) WithPayload(payload *models.Error) *GetAgentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agent bad request response
func (o *GetAgentBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentUnauthorizedCode is the HTTP code returned for type GetAgentUnauthorized
const GetAgentUnauthorizedCode int = 401

/*GetAgentUnauthorized Unauthorized.

swagger:response getAgentUnauthorized
*/
type GetAgentUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAgentUnauthorized creates GetAgentUnauthorized with default headers values
func NewGetAgentUnauthorized() *GetAgentUnauthorized {

	return &GetAgentUnauthorized{}
}

// WithPayload adds the payload to the get agent unauthorized response
func (o *GetAgentUnauthorized) WithPayload(payload *models.Error) *GetAgentUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agent unauthorized response
func (o *GetAgentUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentForbiddenCode is the HTTP code returned for type GetAgentForbidden
const GetAgentForbiddenCode int = 403

/*GetAgentForbidden Forbidden.

swagger:response getAgentForbidden
*/
type GetAgentForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAgentForbidden creates GetAgentForbidden with default headers values
func NewGetAgentForbidden() *GetAgentForbidden {

	return &GetAgentForbidden{}
}

// WithPayload adds the payload to the get agent forbidden response
func (o *GetAgentForbidden) WithPayload(payload *models.Error) *GetAgentForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agent forbidden response
func (o *GetAgentForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentNotFoundCode is the HTTP code returned for type GetAgentNotFound
const GetAgentNotFoundCode int = 404

/*GetAgentNotFound Not Found.

swagger:response getAgentNotFound
*/
type GetAgentNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAgentNotFound creates GetAgentNotFound with default headers values
func NewGetAgentNotFound() *GetAgentNotFound {

	return &GetAgentNotFound{}
}

// WithPayload adds the payload to the get agent not found response
func (o *GetAgentNotFound) WithPayload(payload *models.Error) *GetAgentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agent not found response
func (o *GetAgentNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentInternalServerErrorCode is the HTTP code returned for type GetAgentInternalServerError
const GetAgentInternalServerErrorCode int = 500

/*GetAgentInternalServerError Error.

swagger:response getAgentInternalServerError
*/
type GetAgentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAgentInternalServerError creates GetAgentInternalServerError with default headers values
func NewGetAgentInternalServerError() *GetAgentInternalServerError {

	return &GetAgentInternalServerError{}
}

// WithPayload adds the payload to the get agent internal server error response
func (o *GetAgentInternalServerError) WithPayload(payload *models.Error) *GetAgentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agent internal server error response
func (o *GetAgentInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
