// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAgentHandlerFunc turns a function with the right signature into a get agent handler
type GetAgentHandlerFunc func(GetAgentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAgentHandlerFunc) Handle(params GetAgentParams) middleware.Responder {
	return fn(params)
}

// GetAgentHandler interface for that can handle valid get agent params
type GetAgentHandler interface {
	Handle(GetAgentParams) middleware.Responder
}

// NewGetAgent creates a new http.Handler for the get agent operation
func NewGetAgent(ctx *middleware.Context, handler GetAgentHandler) *GetAgent {
	return &GetAgent{Context: ctx, Handler: handler}
}

/* GetAgent swagger:route GET /agents/{agent_id} swarm getAgent

Get specific agent.

*/
type GetAgent struct {
	Context *middleware.Context
	Handler GetAgentHandler
}

func (o *GetAgent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAgentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
