// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HealthNoContentCode is the HTTP code returned for type HealthNoContent
const HealthNoContentCode int = 204

/*HealthNoContent Success.

swagger:response healthNoContent
*/
type HealthNoContent struct {
}

// NewHealthNoContent creates HealthNoContent with default headers values
func NewHealthNoContent() *HealthNoContent {

	return &HealthNoContent{}
}

// WriteResponse to the client
func (o *HealthNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
