// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAgentsHandlerFunc turns a function with the right signature into a list agents handler
type ListAgentsHandlerFunc func(ListAgentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAgentsHandlerFunc) Handle(params ListAgentsParams) middleware.Responder {
	return fn(params)
}

// ListAgentsHandler interface for that can handle valid list agents params
type ListAgentsHandler interface {
	Handle(ListAgentsParams) middleware.Responder
}

// NewListAgents creates a new http.Handler for the list agents operation
func NewListAgents(ctx *middleware.Context, handler ListAgentsHandler) *ListAgents {
	return &ListAgents{Context: ctx, Handler: handler}
}

/* ListAgents swagger:route GET /agents swarm listAgents

List all running agents.

*/
type ListAgents struct {
	Context *middleware.Context
	Handler ListAgentsHandler
}

func (o *ListAgents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListAgentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
